name: Deploy AI to Azure B2

on:
  push:
    branches:
      - main
    paths:
      - 'face-attendance/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server:  identifaceacr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        cd face-attendance
        
        docker build -t identifaceacr.azurecr.io/identiface-ai:latest .
        docker push identifaceacr.azurecr.io/identiface-ai:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'identiface-ai-api'
        publish-profile: ${{ secrets.AZURE_AI_WEBAPP_PUBLISH_PROFILE }}
        images: ' identifaceacr.azurecr.io/identiface-ai:latest'